<?php
/**
 * @file
 * µMenu module.
 */

/**
 * Get menu storage service
 *
 * @return \MakinaCorpus\Umenu\DrupalMenuStorage
 *
 * @deprecated
 */
function umenu_get_storage() {
  return \Drupal::service('umenu.menu_storage');
}

/**
 * Get the tree manager service
 *
 * @return \MakinaCorpus\Umenu\TreeManager
 *
 * @deprecated
 */
function umenu_get_manager() {
  return \Drupal::service('umenu.manager');
}

/**
 * Implements hook_theme().
 */
function umenu_theme() {
  return [
    'umenu' => [
      'variables' => ['tree' => null, 'name' => null, 'current' => null],
      'template' => 'views/umenu',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_umenu(&$variables, $hook) {
  if (isset($variables['name'])) {
    $variables['theme_hook_suggestions'][] = 'umenu__' . str_replace('-', '_', $variables['name']);
  }
  if ($hook !== $variables['theme_hook_original']) {
    $variables['theme_hook_suggestions'][] = $variables['theme_hook_original'];
    if (isset($variables['name'])) {
      $variables['theme_hook_suggestions'][] = $variables['theme_hook_original'] . '__' . str_replace('-', '_', $variables['name']);
    }
  }
  if (!isset($variables['current'])) {
    if ($node = menu_get_object()) {
      $variables['current'] = $node->nid;
    }
  }
}
